<?php

/**
 * Allowances
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package	##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author	 ##NAME## ##EMAIL##
 * @version	SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Allowances extends BaseAllowances { 

	/**
	 *	Get All by Status
	 */
	public function getAllowances($user_id = 0, $active = array(0,1)) {
		try {
			$query = Doctrine_Query::create()
									->select('a.*')
									->from('Allowances a')
									->whereIn('a.active', $active);

			if( ! empty($user_id) ) {
				$query->andWhere('a.user_id = ?', $user_id);
			}

			$query = $query->execute();

			$count = $query->count();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($count) ) ? null:$query;
	}
	// END

	/**
	 *	By ID
	 */
	public function getAllowanceById($id) {
		try {
			$query = Doctrine_Query::create()
									->select('a.*, ac.*, c.*, t.*')
									->from('Allowances a')
									->leftJoin('a.AllowanceConfigs ac')
									->leftJoin('ac.Configurations c')
									->leftJoin('c.Types t')
									->where('a.id = ?', $id)
									->orderBy('ac.display_order')
									->execute();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}
	// END

	/**
	 *	Many for User
	 */
	public function getAllowancesByUserId($user_id = 0, $active = array(0,1)) {
		try {
			$query = Doctrine_Query::create()
									->select('a.*, e.*, ea.*, dd.*')
									->from('Allowances a')
									->leftJoin('a.Events e')
									->leftJoin('e.Earnings ea')
									->leftJoin('e.Deductions dd')
									->where('a.user_id = ?', $user_id)
									->andWhereIn('a.active', $active)
									->execute(array(), Doctrine::HYDRATE_ARRAY);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}
	// END

	/**
	 *	Single for Stub
	 */
	public function getAllowanceByIdForStub($id) {
		try {
			$query = Doctrine_Query::create()
									->select('a.*, ac.*, c.*, t.*')
									->from('Allowances a')
									->leftJoin('a.AllowanceConfigs ac')
									->leftJoin('ac.Configurations c')
									->leftJoin('c.Types t')
									->where('a.id = ?', $id)
									->orderBy('ac.display_order')
									->execute();
			$count = $query->count();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($count) ) ? null:$query;
	}
	// END




	/**
	 *	By ID
	 */
	public function getAdminAllowanceById($id) {
		try {
			$query = Doctrine_Query::create()
									->select('a.*, ac.*, c.*, t.*, u.*')
									->from('Allowances a')
									->leftJoin('a.AllowanceConfigs ac')
									->leftJoin('ac.Configurations c')
									->leftJoin('c.Types t')
									->innerJoin('a.Users u')
									->where('a.id = ?', $id)
									->orderBy('ac.display_order')
									->execute();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}
	// END


}
// END CLASS