<?php

/**
 * Earnings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package	##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author	 ##NAME##
 * @version	SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Earnings extends BaseEarnings {


	public function getOrCreateEarningsByEventId($id, $allowance_id = 0, $earnings = array()) {

		$Y = date("Y")."-01-01 00:00:00";

		foreach($earnings as $row) {
			$count = null;
			try {
				$query = Doctrine_Query::create()
										->select('ea.*')
										->from('Earnings ea')
										->where('ea.event_id = ?', $id)
										->andWhere('ea.config_id = ?', $row['id'])
										->execute();
				$count = $query->count();
			} catch(Exception $e) {
				Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
			}

			if( empty($count) ) {
				$query 	= new Earnings();
				$data 	= array(
								'event_id' 	=> $id,
								'config_id' => $row['id'],
								'amount' 	=> $row['current']['amount']
							);
				$query->fromArray($data);
				$query->save();
			}
			else { 
				if($query->{0}->amount != $row['current']['amount']) {
					$query->{0}->amount = $row['current']['amount'];
					$query->save();
				}
			}
		}

		$query = null;

		try {
			$query = Doctrine_Query::create()
									->select('ea.*, e.*')
									->from('Earnings ea')
									->leftJoin('ea.Events e')
									->where('e.allowance_id = ?', $allowance_id)
									->andWhere('e.created > ?', $Y)
									->execute(array(), Doctrine::HYDRATE_ARRAY);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}

		return ( empty($query) ) ? null:$query;
	}


}
// END CLASS