<?php

/**
 * Geoloc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package	##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author	 ##NAME## ##EMAIL##
 * @version	SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Geoloc extends BaseGeoloc
{

	public function getStateOptions() {
		try {
			$query = Doctrine_Query::create()
									->select('g.state_abbr, g.state')
									->from('Geoloc g')
									->groupBy('g.state_abbr')
									->execute(array(), Doctrine::HYDRATE_ARRAY);

			$options = array();
			foreach($query as $row) {
				$options[$row['state_abbr']] = $row['state'];
			}

		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($options) ) ? array():$options;
	}

}