<?php

/**
 * Issues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME##
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Issues extends BaseIssues
{

	public function getIssues() {
		try {
			$query = Doctrine_Query::create()
									->select('i.*, ic.*')
									->from('Issues i')
									->leftJoin('i.IssueComments ic')
									->execute();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function getIssuesByReferer($referer = null, $_is_admin = false) {
		try {

			$active = ( $_is_admin ) ? array(0,1):array(1);
			$query 	= array();
			$topics = Doctrine_Query::create()
									->select('i.*')
									->from('Issues i')
									->where('i.referer = ?', $referer)
									->execute();

			$count = $topics->count();
			if( ! empty($count) ) {

				foreach($topics as $row) {

					$set = Doctrine_Query::create()
										->select('i.*, ic.*')
										->from('Issues i')
										->leftJoin('i.IssueComments ic')
										->where('i.topic = ?', $row->topic)
										->andWhere('i.referer = ?', $referer)
										->andWhereIn('ic.active', $active)
										->execute(array(), Doctrine::HYDRATE_ARRAY);

					if( empty($set) ) {
						$set = $row->toArray();
						$set['IssueComments'] = array();
						$query[$row->topic][] = $set;
					} else {
						$query[$row->topic] = $set;
					}
				}
			}
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function updateIssue($id, $post) {
		try {
			$query = Doctrine::getTable('Issues')->find($id);
			$query->fromArray($post);
			$query->save();
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? false:true;
	}
	// END

}
// END CLASS