<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package	##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author	 ##NAME##
 * @version	SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users extends BaseUsers {


	public function getUsers($active = array(0,1)) {
		try {
			$query = Doctrine_Query::create()
									->select('u.*, m.*')
									->from('Users u')
									->leftJoin('u.Members m')
									->whereIn('u.active', $active)
									->execute();

		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function getUserById($id) {
		try {
			$query = Doctrine_Query::create()
									->select('u.*, m.*')
									->from('Users u')
									->leftJoin('u.Members m')
									->where('u.id = ?', $id)
									->execute(array(), Doctrine::HYDRATE_ARRAY);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function getAdminUserById($id) {
		try {
			$query = Doctrine::getTable('Users')->find($id);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}


	public function getUserRecordById($id) {
		try {
			$query = Doctrine::getTable('Users')->find($id);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function getUserByUniqueId($uid) {
		try {
			$query = Doctrine::getTable('Users')->findByUniqueId($uid);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function getUserFromEmail($email) {
		try {
			$query = Doctrine_Query::create()
									->select('u.*, m.*')
									->from('Users u')
									->leftJoin('u.Members m')
									->where('m.email = ?', $email)
									->execute(array(), Doctrine::HYDRATE_ARRAY);
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

	public function saveUser($id, $data = array()) {

		try {
			if( empty($id) ) {
				$query = new Users();
				$query->fromArray($data);
				$query->save();
				return ( empty($query) ) ? false:$query->id;
			} else {
				$query = Doctrine::getTable('Users')->find($id);
				$query->fromArray($data);
				$query->save();
				return ( empty($query) ) ? false:true;
			}
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
	}

	public function getUserOptions() {
		try {

			$query = Doctrine_Query::create()
									->select('u.id, u.screenname AS label')
									->from('Users u')
									->execute(array(), Doctrine::HYDRATE_ARRAY);
			if( count($query) > 0 ) {
				$options = array();
				foreach($query as $row) {
					$options[$row['id']] = $row['label'];
				}
			}
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($options) ) ? array():$options;
	}
	// END

	public function getActivity($id) {
		try{ 
			$user 		= self::getUserRecordById($id);
			if( ! empty($user) ) {
				$activity 	= array(
									'editor' 	=> array('id' => $user->id, 'screenname' => $user->screenname),
									'updated' 	=> array('updated' => $user->updated, 'stt' => strtotime($user->updated)),
									'lastlogin' => array('lastlogin' => $user->lastlogin, 'stt' => strtotime($user->lastlogin))
								);
			}
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($activity) ) ? array():$activity;
	}
	// END

	public function getUniqueIdById($id) {
		try {
			$query = Doctrine::getTable('Users')->find($id)->unique_id;
		} catch(Exception $e) {
			Core_Logger::getInstance()->err(__METHOD__ . " - " . $e);
		}
		return ( empty($query) ) ? null:$query;
	}

}