<?php 
?>
<div class="table">
	<div class="tr">
		<div class="td wide">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Allowances</h2>
							<h3><?= ( empty($this->data->allowance->id) ) ? 'New Allowance':$this->data->allowance->label."&rsquo;s"; ?> Set Up</h3>
						</hgroup>
					</header><?
					if( ! $this->data->userHasAllowances): ?>
						<?= $this->render('templates/allowances.detail.tpl'); ?><?
					endif; ?>
					<?= $this->data->allowance->form; ?>
				</section>
			</div>
		</div>
		<div class="td gutter">&nbsp;</div>
		<div class="td side">
			<div class="pad">
				<aside>
					<header>
						<h4>Activity</h4>
					</header>
					<?= $this->render('index/sidebar.phtml'); ?>
				</aside>

				<br />

				<?= $this->render('index/section.phtml'); ?>

				<?
				if( ! empty($this->data->allowance->id) ): ?>
				<aside>
					<header>
						<h5><?= $this->data->allowance->label; ?>&rsquo;s Allowance</h5>
					</header>
					<ul>
						<li>Set Up</li>
						<li><a href="/allowances/stub/id/<?= $this->data->allowance->id; ?>/">Current Stub</a></li>
						<li><a href="/allowances/history/id/<?= $this->data->allowance->id; ?>/">History</a></li>
					</ul>
				</aside><? 
				endif; ?>
			</div>
		</div>
		<div class="td exp">&nbsp;</div>
	</div>
</div>
<script type="text/javascript">
	base.forms.init();
	base.widget.init();
</script>
