<?php 
	//Core_P::p($this->data->pay, 1);
?>
<div class="table">
	<div class="tr">
		<div class="td wide">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Allowances</h2>
							<h3><?= $this->data->allowance->label; ?>&rsquo;s Current Stub</h3>
						</hgroup>
					</header>
				</section>
				<article>
					<fieldset class="stats">
						<legend><span><?= $this->data->allowance->label; ?></span></legend>
						<ol>
							<li><dl><dt>Rate</dt><dd><?= $this->data->pay->base->rate; ?></dd></dl></li><li><dl><dt>Interval</dt><dd><?= $this->data->pay->base->interval; ?></dd></dl></li><li><dl><dt>Period From</dt><dd><?= $this->data->pay->base->period_from; ?></dd></dl></li><li><dl><dt>Period To</dt><dd><?= $this->data->pay->base->period_to; ?></dd></dl></li>
						</ol>
					</fieldset>

				<?
				if( count((array) $this->data->pay->earnings) > 0 ): ?>
					<fieldset class="details">
						<legend><span>Earnings</span></legend><? 
					foreach($this->data->pay->earnings as $row): ?>
						<ol>
							<li class="label"><?= $row->label; ?></li>
							<li><dl><dt>Current</dt><dd><?= $row->current->string; ?></dd></dl></li><li><dl><dt>YTD</dt><dd><?= $row->ytd->string; ?></dd></dl></li>
						</ol><?
					endforeach; ?>
					</fieldset><?
				endif; ?>

				<?
				if( count((array) $this->data->pay->deductions) > 0 ): ?>
					<fieldset class="details minus">
						<legend><span>Deductions</span></legend><? 
					foreach($this->data->pay->deductions as $row): ?>
						<ol>
							<li class="label"><?= $row->label; ?></li>
							<li><dl><dt>Current</dt><dd><?= $row->current->string; ?></dd></dl></li><li><dl><dt>YTD</dt><dd><?= $row->ytd->string; ?></dd></dl></li>
						</ol><?
					endforeach; ?>
					</fieldset><?
				endif; ?>

				<?
				if( count((array) $this->data->pay->net) > 0 ): ?>
					<fieldset class="details">
						<legend><span>Net</span></legend>
						<ol>
							<li><dl><dt>Current</dt><dd><?= $this->data->pay->net->current->string; ?></dd></dl></li><li><dl><dt>YTD</dt><dd><?= $this->data->pay->net->ytd->string; ?></dd></dl></li>
						</ol>
					</fieldset><?
				endif; ?>

				</article>

				<p class="submit-block">
					<a href="javascript:void(0);" class="print"><button>Print Stub</button></a>
				</p>
			</div>
		</div>
		<div class="td gutter">&nbsp;</div>
		<div class="td side">
			<div class="pad">
				<aside>
					<header>
						<h4>Activity</h4>
					</header>
					<?= $this->render('index/sidebar.phtml'); ?>
				</aside>

				<br />

				<?= $this->render('index/section.phtml', $this->data); ?>

				<aside>
					<header>
						<h5><?= $this->data->allowance->label; ?>&rsquo;s Allowance</h5>
					</header>
					<ul>
						<li><a href="/allowances/allowance/id/<?= $this->data->allowance->id; ?>/">Set Up</a></li>
						<li>Current Stub</li>
						<li><a href="/allowances/history/id/<?= $this->data->allowance->id; ?>/">History</a></li>
					</ul>
				</aside>
			</div>
		</div>
		<div class="td exp">&nbsp;</div>
	</div>
</div>
<script type="text/javascript">
	base.forms.init();
</script>