<?php 

?>
<div class="table">
	<div class="tr">
		<div class="td narrow">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Log In</h2>
						</hgroup>
					</header>
					<?= $this->data->login->form; ?>
				</section>
				<br />
				<section>
					<?= $this->data->forgot->form; ?>
				</section>
			</div>
		</div>
		<div class="td gutter">&nbsp;</div>
		<div class="td wide">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Sign Up</h2>
						</hgroup>
					<?= $this->data->signup->form; ?>
					</header>
				</section>
			</div>
		</div>
		<div class="td exp">&nbsp;</div>
	</div>
</div>
<script type="text/javascript">
	base.forms.init();
</script>
