<?php 
	//Core_P::p($this->data->admin, 1);
?>
<div class="table">
	<div class="tr">
		<div class="td wide">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Admin</h2>
							<h3>User</h3>
						</hgroup>
					</header>
					<?= $this->data->profile->form; ?>
				</section>
			</div>
		</div>
		<div class="td gutter">&nbsp;</div>
		<div class="td side">
			<div class="pad">
				<aside>
					<header>
						<h4>Admin</h4> 
					</header>
					<ul class="section">
						<li><a href="/admin/users">users</a></li>
						<li><a href="/admin/settings">settings</a></li>
						<li><a href="/admin/allowances">allowances</a></li>
					</ul>
				</aside>

				<? if($this->data->is_detail): ?>
				<br />

				<aside>
					<header>
						<h4><?= $this->data->admin->user->screenname; ?>&rsquo;s</h4> 
					</header>
					<ul class="section">
						<li>profile</li>
						<li><a href="/admin/settings/user_id/<?= $this->data->admin->user->id; ?>/">settings</a></li>
						<li><a href="/admin/allowances/user_id/<?= $this->data->admin->user->id; ?>/">allowances</a></li>
					</ul>
				</aside>
				<? endif; ?>

			</div>
		</div>
		<div class="td exp">&nbsp;</div>
	</div>
</div>
<script type="text/javascript">
	base.forms.init();
</script>
