<?php 
?>
<script type="text/javascript" src="/assets/js/jquery.issues.js"></script>
<div class="content tracker corners">
	<div class="table">
		<div class="tr">
			<div class="td full">
				<div class="pad">
					<h4>Contextual Issue Tracking</h4>
					<div id="issues"></div>
				</div>
			</div>
			<div class="td exp">&nbsp;</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	issues.tracker.init();
</script>
