<?php 
?>
<div class="table">
	<div class="tr">
		<div class="td full">
			<div class="pad">
				<section>
					<header>
						<hgroup>
							<h2>Oops</h2>
						</hgroup>
					</header>
				</section>
				<p>
					<?= (empty($this->message) ? '':$this->message); ?>
				</p>
				<? if(APPLICATION_ENV == 'development'): ?>
				<h4>Exception information:</h4>
				<p>
					<?= 'Error Code '.$this->code; ?>
				</p>
				
				<h4>Stack trace:</h4> 
				<pre style="font: 8pt/10pt Arial;">
					<?= $this->exception->getTraceAsString(); ?> 
				</pre><br />
				
				<h4>Request Parameters:</h4> 
				<pre>
				<? var_dump($this->request->getParams()); ?> 
				</pre>
				<? endif; ?>
			</div>
		</div>
		<div class="td gutter">&nbsp;</div>
	</div>
</div>