<?php 
?>
<footer>
	<div class="table">
		<div class="tr">
			<div class="td wide">
				<div class="pad">
					<section>
						<small>html5 (experimental)</small>
					</section>
				</div>
			</div>
			<div class="td gutter">&nbsp;</div>
			<div class="td side">
				<div class="pad">
					<aside>
						&copy; copyright <?= date('Y');?>, <a href="http://www.dprockcreative.com/" rel="external">d.prock creative inc</a>.

						<ul>
							<li><a href="/templates/internal/privacy" class="internal" rel="#ol">privacy policy</a></li>
							<li><a href="/templates/internal/terms" class="internal" rel="#ol">terms &amp; conditions</a></li>
						</ul>
					</aside>
				</div>
			</div>
			<div class="td exp">&nbsp;</div>
		</div>
	</div>
</footer>

