<?php 

	$issues = ( empty(Zend_Registry::get('config')->issue->tracking) ) ? false:true; 

	//Core_P::p(Zend_Registry::get('config'), 1);

	if( isset($this->data->meta_keywords) ) {
		$this->headMeta()->appendName('keywords', $this->data->meta_keywords);
	}
	if( isset($this->data->meta_description) ) {
		$this->headMeta()->appendName('description', $this->data->meta_description);
	}

	$this->headLink()
		->headLink(array('rel' => 'icon', 'href' => '/assets/img/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND')
		->headLink(array('rel' => 'shortcut icon', 'href' => '/assets/img/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND')
		->appendStylesheet('/assets/css/print.css', 'print', true)
		->appendStylesheet('/assets/css/base.css', 'screen', true);

	if( $issues ) {
		$this->headLink()->appendStylesheet('/assets/css/issues.css', 'screen', true);
	}

	$this->headLink()->appendStylesheet('/assets/css/ie.css', 'screen', 'IE');

	$this->headMeta()
		->setCharset('utf-8')
		->appendHttpEquiv('Expires', date("D, d M Y H:i:s T", (time() - 86400)))
		->appendHttpEquiv('imagetoolbar', 'no')
		->appendName('author', 'd.prock creative, Inc.')
		->appendName('keywords', 'MyKidsAllowance, parents, parenting, allowances, allowance, children, kids, online tools, d.prock creative')
		->appendName('description', "A site built to help parents manage Allowances for their children.");

	$this->headScript()
		->appendFile('/assets/js/jquery.base.js', 'text/javascript')
		->appendFile('http://html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'IE'));
?>
<?= $this->doctype(); ?>

<html lang="en">
<head>
<?= $this->headTitle().PHP_EOL.$this->headLink().PHP_EOL.$this->headMeta().PHP_EOL.$this->headScript(); ?>
</head>
<body id="top">
	<div id="container">	
		<div id="content"><? 
		if( ! empty(Zend_Registry::get('config')->site->default->online) ): ?>
			<div class="content minipage corners">
<?= $this->render('nav/index.phtml'); ?>
			</div>
			<header>
				<hgroup>
					<h1 id="logo"><a href="/">My Kid&rsquo;s Allowance</a></h1>
				</hgroup>
			</header><br /><? 
		endif; ?>
			<div class="content corners">
<?= $this->layout()->content; ?>
			</div>
<?= ($issues) ? $this->render('issue/index.phtml'):''; ?>
			<div class="footer">
<?= $this->render('footer/index.phtml'); ?>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		base.common.init();
	</script>
	<div id="ol" class="modal"><div class="close"><span>'esc' to close</span></div><div class="display-wrapper"><div class="display"></div></div></div>
</body>
</html>

